name: CSE 15L Lab Reports

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y
      - name: Generate PDF
        run: |
          find . -type f -name 'lab*.html' | while read file; do
            base_url="https://yariazen.github.io/cse15l-lab-reports"
            filename=$(basename "$file" .html)
            weeknum=$(basename $(dirname "$(dirname "$file")"))
            url="${base_url}/${weeknum}/${filename}.html"
            google-chrome --headless --print-to-pdf="$(basename "$file" .md).pdf" "$url"
          done
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Lab Reports
          path: ./lab*.pdf
          compression-level: fastest
      
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
